{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sason-max.gradle",
    "module": "plugins",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "eo6jrzrjmzginfiqijsdmdumde"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugins-1.0.5.jar",
          "url": "plugins-1.0.5.jar",
          "size": 121100,
          "sha512": "512bca09d14a97e51e343e7600073bc0a93c725f4e13be4f3c291dd76c2d76f96a92e1adef61d8fdb45f8f2e121278e41e09190a987beebc45662b44035551e7",
          "sha256": "de8bc47d166d44e82366cfe62248e5b71fd4c47bc0c9e292f9ab11a4beb1b6c5",
          "sha1": "381b4d54aeefa56bc51bd9c4cecd337809da4492",
          "md5": "09b205da48abc895a90fb1cc94e07cb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "plugins-1.0.5.jar",
          "url": "plugins-1.0.5.jar",
          "size": 121100,
          "sha512": "512bca09d14a97e51e343e7600073bc0a93c725f4e13be4f3c291dd76c2d76f96a92e1adef61d8fdb45f8f2e121278e41e09190a987beebc45662b44035551e7",
          "sha256": "de8bc47d166d44e82366cfe62248e5b71fd4c47bc0c9e292f9ab11a4beb1b6c5",
          "sha1": "381b4d54aeefa56bc51bd9c4cecd337809da4492",
          "md5": "09b205da48abc895a90fb1cc94e07cb4"
        }
      ]
    }
  ]
}
