{
  "formatVersion": "1.1",
  "component": {
    "group": "com.season-max.gradle",
    "module": "plugins",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "oytrx44b6vafzcd2g5e7aowipq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugins-1.0.5.jar",
          "url": "plugins-1.0.5.jar",
          "size": 125313,
          "sha512": "03af20a3e443a1e1b41e6c9f5fb7ee0044d3dfaf67b78ce2a5ae748c35de0a2911870f0f3cf5c5ee65afee3fe8c7223bd7ae0fb2f480dd85872e4d849e4e7c6f",
          "sha256": "adaff8d53e3a38c11fc158692f766bc86ec061bf1ad33b1c88d8219c040bd23f",
          "sha1": "a76de5dbd7122a58d3cd373a9175ce35846cccf0",
          "md5": "ee69ed46219d11caa42110c1d1ae4ae0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "plugins-1.0.5.jar",
          "url": "plugins-1.0.5.jar",
          "size": 125313,
          "sha512": "03af20a3e443a1e1b41e6c9f5fb7ee0044d3dfaf67b78ce2a5ae748c35de0a2911870f0f3cf5c5ee65afee3fe8c7223bd7ae0fb2f480dd85872e4d849e4e7c6f",
          "sha256": "adaff8d53e3a38c11fc158692f766bc86ec061bf1ad33b1c88d8219c040bd23f",
          "sha1": "a76de5dbd7122a58d3cd373a9175ce35846cccf0",
          "md5": "ee69ed46219d11caa42110c1d1ae4ae0"
        }
      ]
    }
  ]
}
