{
  "formatVersion": "1.1",
  "component": {
    "group": "com.season-max.gradle",
    "module": "plugins",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "pv5gnm6gbbg5rlt2c4zmsjfbgy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugins-1.0.5.jar",
          "url": "plugins-1.0.5.jar",
          "size": 130978,
          "sha512": "2cb62c2909ae84dd80beeb926e27b7c32458a06a6057ab9f9e2461da4618af3c25db9b9656f1023954ec5dba96c5bd70f9b2ef54f4ee7a8b91abd78d4519da75",
          "sha256": "df4e4d0fa9ec2bd494ca03e02b9e050a91d894346edba367b16c7801d7439375",
          "sha1": "f5ac175fa6a5ade986197969e1f54d644c3cc84e",
          "md5": "42ae3f138e99e1528dc596261a56865b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "plugins-1.0.5.jar",
          "url": "plugins-1.0.5.jar",
          "size": 130978,
          "sha512": "2cb62c2909ae84dd80beeb926e27b7c32458a06a6057ab9f9e2461da4618af3c25db9b9656f1023954ec5dba96c5bd70f9b2ef54f4ee7a8b91abd78d4519da75",
          "sha256": "df4e4d0fa9ec2bd494ca03e02b9e050a91d894346edba367b16c7801d7439375",
          "sha1": "f5ac175fa6a5ade986197969e1f54d644c3cc84e",
          "md5": "42ae3f138e99e1528dc596261a56865b"
        }
      ]
    }
  ]
}
