{
  "formatVersion": "1.1",
  "component": {
    "group": "com.season-max.gradle",
    "module": "plugins",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "qgeobib5yraz5mush7ri52tw4m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugins-1.0.5.jar",
          "url": "plugins-1.0.5.jar",
          "size": 128750,
          "sha512": "b352b610d93d3198e38ceb2c242e13ad48353cf5a882456e6dacca28958bb53622dd76c3e32edd328eb1944ce34dcc9d482701aae99466e46aa141a542ecf8c6",
          "sha256": "14d94e907a8ef5da012e1d4f5cd46e1ad89adb7c2ec9c191cd6c6ad281aad8b6",
          "sha1": "6a16d899d50a5bcb2996fc0edca0eb9080865d56",
          "md5": "816a20908179d31febcba707280f62d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "plugins-1.0.5.jar",
          "url": "plugins-1.0.5.jar",
          "size": 128750,
          "sha512": "b352b610d93d3198e38ceb2c242e13ad48353cf5a882456e6dacca28958bb53622dd76c3e32edd328eb1944ce34dcc9d482701aae99466e46aa141a542ecf8c6",
          "sha256": "14d94e907a8ef5da012e1d4f5cd46e1ad89adb7c2ec9c191cd6c6ad281aad8b6",
          "sha1": "6a16d899d50a5bcb2996fc0edca0eb9080865d56",
          "md5": "816a20908179d31febcba707280f62d6"
        }
      ]
    }
  ]
}
