{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhangyue.gradle.plugins",
    "module": "plugin_privacy",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "x4rg467yfvg4xkahdjldw2n62q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin_privacy-1.0.0.jar",
          "url": "plugin_privacy-1.0.0.jar",
          "size": 66320,
          "sha512": "9aa0e03621ec8575d58e98abf424e067c511220fd145ca8713bf137cada9a00bbf7ba12f8243c9cbdb05f0407d0d2627d48a1ca141439c23d0e465bcacac8bd8",
          "sha256": "79fe8ed3437be4160b4af0394295591ae7b7ec460256d11db669900fc4378faf",
          "sha1": "28f5ce8b9d5ad8fc59d426e43ebfd96f2f3cbf2e",
          "md5": "0a0db499d4bc7057c252e7bcc9c6536d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "plugin_privacy-1.0.0.jar",
          "url": "plugin_privacy-1.0.0.jar",
          "size": 66320,
          "sha512": "9aa0e03621ec8575d58e98abf424e067c511220fd145ca8713bf137cada9a00bbf7ba12f8243c9cbdb05f0407d0d2627d48a1ca141439c23d0e465bcacac8bd8",
          "sha256": "79fe8ed3437be4160b4af0394295591ae7b7ec460256d11db669900fc4378faf",
          "sha1": "28f5ce8b9d5ad8fc59d426e43ebfd96f2f3cbf2e",
          "md5": "0a0db499d4bc7057c252e7bcc9c6536d"
        }
      ]
    }
  ]
}
