{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhangyue.gradle.plugins",
    "module": "plugin_privacy",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "3ofxpj7fqvbaliup7dwmb6s4gi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin_privacy-1.0.0.jar",
          "url": "plugin_privacy-1.0.0.jar",
          "size": 66368,
          "sha512": "aff070fe43083a84b922d7b8b29f2f2c7d2273922809c8ec5edf60e08f69a1244cc3f49050b8561fe93d9d19cb5730b6ac90b35a5242e4891ba668c7a5d7e9a0",
          "sha256": "0b75892db8fb9cd33a2a1e8f3f065701e04120884154e3f527762f9d4dcc5094",
          "sha1": "75eeb4d31842231bf12cea366023891043a3fae4",
          "md5": "cf6d63f9dd6cf2f834dd24b1288d1687"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "plugin_privacy-1.0.0.jar",
          "url": "plugin_privacy-1.0.0.jar",
          "size": 66368,
          "sha512": "aff070fe43083a84b922d7b8b29f2f2c7d2273922809c8ec5edf60e08f69a1244cc3f49050b8561fe93d9d19cb5730b6ac90b35a5242e4891ba668c7a5d7e9a0",
          "sha256": "0b75892db8fb9cd33a2a1e8f3f065701e04120884154e3f527762f9d4dcc5094",
          "sha1": "75eeb4d31842231bf12cea366023891043a3fae4",
          "md5": "cf6d63f9dd6cf2f834dd24b1288d1687"
        }
      ]
    }
  ]
}
