{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhangyue.gradle.plugins",
    "module": "plugin_privacy",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "ho2aru2w2vcxhptn7niqzzel3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin_privacy-1.0.0.jar",
          "url": "plugin_privacy-1.0.0.jar",
          "size": 66312,
          "sha512": "f6e52a08074e81f991a907ac6861b898f7b01737416ff7b108448856d5057cbb595656a67b23aed23e5e7dda494ba93638a7c72862828f943148e76cfbcc016e",
          "sha256": "1a424996162b9320c9839a69ffe0be9df01b924c61b74e5db546dafb73e32168",
          "sha1": "6eaf5b825399124b00b2ad76d106fc6b6516d23c",
          "md5": "58b011d3a45414b1ff9e59a4a0dfb18a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "plugin_privacy-1.0.0.jar",
          "url": "plugin_privacy-1.0.0.jar",
          "size": 66312,
          "sha512": "f6e52a08074e81f991a907ac6861b898f7b01737416ff7b108448856d5057cbb595656a67b23aed23e5e7dda494ba93638a7c72862828f943148e76cfbcc016e",
          "sha256": "1a424996162b9320c9839a69ffe0be9df01b924c61b74e5db546dafb73e32168",
          "sha1": "6eaf5b825399124b00b2ad76d106fc6b6516d23c",
          "md5": "58b011d3a45414b1ff9e59a4a0dfb18a"
        }
      ]
    }
  ]
}
